spring:
  application:
    name: wallet-service
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:momentum}
    username: ${POSTGRES_USER:momentum}
    password: ${POSTGRES_PASSWORD:momentum}
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_DEFAULT_USER:momentum}
    password: ${RABBITMQ_DEFAULT_PASS:momentum}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
wallet:
  messaging:
    command-queue: wallet.commands.queue
    command-exchange: wallet.commands
    debit-routing-key: wallet.debit.command
    credit-routing-key: wallet.credit.command
    event-exchange: wallet.events
    transaction-result-routing-key: wallet.transaction.result
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
