spring:
  application:
    name: transfer-service
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:momentum}
    username: ${POSTGRES_USER:momentum}
    password: ${POSTGRES_PASSWORD:momentum}
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: 5672
    username: ${RABBITMQ_DEFAULT_USER:momentum}
    password: ${RABBITMQ_DEFAULT_PASS:momentum}

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "health,info"

transfer:
  messaging:
    wallet-command-exchange: wallet.commands
    wallet-debit-routing-key: wallet.debit.command
    wallet-credit-routing-key: wallet.credit.command
    wallet-transaction-result-exchange: wallet.events
    wallet-transaction-result-queue: wallet.transaction-results
    wallet-transaction-result-routing-key: wallet.transaction.result
    transfer-event-exchange: transfer.events
    transfer-completed-routing-key: transfer.completed.event
    transfer-failed-routing-key: transfer.failed.event
    transfer-compensation-routing-key: transfer.compensation.event
